In [1]:
import numpy as np

# X = (hours sleeping, hours studying), y = score on test
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
y = np.array(([92], [86], [89]), dtype=float)

# scale units
X = X/np.amax(X, axis=0) # maximum of X array
y = y/100 # max test score is 100

In [32]:
class Neural_Network(object):
  def __init__(self):
    #parameters
    self.inputSize = 2
    self.outputSize = 1
    self.hiddenSize = 3
    
    #weights
    self.W1 = np.random.randn(self.inputSize, self.hiddenSize) # (3x2) weight matrix from input to hidden layer
    self.W2 = np.random.randn(self.hiddenSize, self.outputSize) # (3x1) weight matrix from hidden to output layer
    
  def forward(self, X):
    #forward propagation through our network
    self.z = np.dot(X, self.W1) # dot product of X (input) and first set of 3x2 weights
    self.z2 = self.sigmoid(self.z) # activation function
    self.z3 = np.dot(self.z2, self.W2) # dot product of hidden layer (z2) and second set of 3x1 weights
    o = self.sigmoid(self.z3) # final activation function
    return o
  
  def backward(self, X, y, o):
    # backward propgate through the network
    self.o_error = y - o # error in output
    self.o_delta = self.o_error*self.sigmoidPrime(o) # applying derivative of sigmoid to error

    self.z2_error = self.o_delta.dot(self.W2.T) # z2 error: how much our hidden layer weights contributed to output error
    self.z2_delta = self.z2_error*self.sigmoidPrime(self.z2) # applying derivative of sigmoid to z2 error

    self.W1 += X.T.dot(self.z2_delta) # adjusting first set (input --> hidden) weights
    self.W2 += self.z2.T.dot(self.o_delta) # adjusting second set (hidden --> output) weights
    
  def sigmoid(self, s):
    # activation function 
    return 1/(1+np.exp(-s))
  
  def sigmoidPrime(self, s):
    #derivative of sigmoid
    return s * (1 - s)
  
  def train (self, X, y):
    o = self.forward(X)
    self.backward(X, y, o)

In [27]:
NN = Neural_Network()
o = NN.forward(X)
print ("Predicted Output:\n" + str(o))
print ("Actual Output:\n" + str(y))    

Predicted Output:
[[ 0.65433515]
 [ 0.6256186 ]
 [ 0.6678103 ]]
Actual Output:
[[ 0.92]
 [ 0.86]
 [ 0.89]]


In [35]:
NN = Neural_Network()
for i in range(1000): # trains the NN 1,000 times
  print ("Input: \n" + str(X))
  print ("Actual Output: \n" + str(y))
  print ("Predicted Output: \n" + str(NN.forward(X)))
  print ("Loss: \n" + str(np.mean(np.square(y - NN.forward(X))))) # mean sum squared loss
  print ("\n")
  NN.train(X, y)

Input: 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.53829662]
 [ 0.54932991]
 [ 0.53322104]]
Loss: 
0.123168198188


Input: 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.56255215]
 [ 0.57791462]
 [ 0.55372002]]
Loss: 
0.10680845006


Input: 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.58524832]
 [ 0.60418139]
 [ 0.57299907]]
Loss: 
0.0926638118208


Input: 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.6065616 ]
 [ 0.62828386]
 [ 0.59122464]]
Loss: 
0.0804009050625


Input: 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[

 [ 0.89]]
Predicted Output: 
[[ 0.90155553]
 [ 0.89661303]
 [ 0.87800652]]
Loss: 
0.000608185389709


Input: 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.90155799]
 [ 0.89659554]
 [ 0.87802344]]
Loss: 
0.000607592980501


Input: 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.90156032]
 [ 0.89657794]
 [ 0.87804018]]
Loss: 
0.000607001630253


Input: 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.90156251]
 [ 0.89656024]
 [ 0.87805675]]
Loss: 
0.000606411332191


Input: 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.90156456]
 [ 0.89654245]
 [ 0.87807314]]
Loss: 
0.000605822079

 [ 0.89]]
Predicted Output: 
[[ 0.90139274]
 [ 0.89288427]
 [ 0.88028953]]
Loss: 
0.000507299653898


Input: 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.9013918 ]
 [ 0.89286712]
 [ 0.88029916]]
Loss: 
0.000506872854962


Input: 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.90139087]
 [ 0.89284997]
 [ 0.88030878]]
Loss: 
0.000506446733158


Input: 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.90138995]
 [ 0.89283285]
 [ 0.8803184 ]]
Loss: 
0.000506021287212


Input: 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.90138902]
 [ 0.89281575]
 [ 0.880328  ]]
Loss: 
0.000505596515

Input: 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.90129239]
 [ 0.89001309]
 [ 0.88192533]]
Loss: 
0.00043865343993


Input: 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.90129219]
 [ 0.8899991 ]
 [ 0.88193343]]
Loss: 
0.000438332599998


Input: 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.90129199]
 [ 0.88998513]
 [ 0.88194151]]
Loss: 
0.000438012239466


Input: 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.90129179]
 [ 0.88997117]
 [ 0.88194959]]
Loss: 
0.000437692357453


Input: 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual 

 [ 0.88357509]]
Loss: 
0.000376830201956


Input: 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.90131028]
 [ 0.88718996]
 [ 0.88358165]]
Loss: 
0.000376598306797


Input: 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.90131058]
 [ 0.88717894]
 [ 0.8835882 ]]
Loss: 
0.000376366730803


Input: 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.90131089]
 [ 0.88716793]
 [ 0.88359475]]
Loss: 
0.000376135473415


Input: 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.9013112 ]
 [ 0.88715693]
 [ 0.88360129]]
Loss: 
0.000375904534076


Input: 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.5